language: java
jdk:
  - openjdk8

# 어느 브랜치가 푸시될 때 수행할지 지정
branches:
  only:
    - master

# Travis CI 서버의 Home
# 의존성은 캐시하여 이후에는 새로 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 push 되었을 때 수행
script: "./gradlew clean build"

# CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hsss0126@gmail.com